# Use an official OpenJDK runtime as a parent image
FROM openjdk:17

# Set the working directory in the container
# WORKDIR /usr/src/app

# Copy the source code
# COPY src src

# Copy the JAR file generated by Jenkins pipeline
COPY build/libs/*.jar springbootapp.jar

# Expose a port if your application listens on a specific port
EXPOSE 8080

# Define the command to run your application
CMD ["java", "-jar", "springbootapp.jar"]
